[IAQSensor]
row = 10
columns = 10
defaultLevel = "GOOD"
timeUnit = "SECONDS"

[[IAQSensor.cell]]
    cellNumber = 62
    level = "MODERATE"
    fromTime = 0

[[IAQSensor.cell]]
    cellNumber = 62
    level = "GOOD"
    fromTime = 500

[[IAQSensor.cell]]
    cellNumber = 62
    level = "MODERATE"
    fromTime = 1200

[[IAQSensor.cell]]
    cellNumber = 63
    level = "MODERATE"
    fromTime = 0
[[IAQSensor.cell]]
    cellNumber = 63
    level = "POOR"
    fromTime = 120

[[IAQSensor.cell]]
    cellNumber = 63
    level = "GOOD"
    fromTime = 160

[[IAQSensor.cell]]
    cellNumber = 63
    level = "VERY_POOR"
    fromTime = 450

[[IAQSensor.cell]]
    cellNumber = 63
    level = "GOOD"
    fromTime = 1200
